version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: blanksql-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=blanksql
    ports:
      - 3306:3306
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data: {}
