name: Test Code on test branch

on:
  pull_request: # push 이벤트 감지
    branches:
      - test # test branch 한정

jobs:
  test-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Run test
        run: npm test
